language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -q 'errbot>=4.3'
  - pip install -q pytest pytest-pep8 --use-wheel
  - pip install -q coverage coveralls --use-wheel
script:
  - coverage run --source pomodoro -m py.test --pep8
after_success:
  - coveralls
notifications:
  email: false
